const {
    itemController,
    dashboardController,
    mainCategoriesController,
    articleCategoriesController,
    productCategoriesController,
    brandController,
    productController,
    articleController,
    subscribeController,
    sliderController,
    contactController,
    settingController,
    orderController,
    couponController,
    deliveryController,
    advertiseController,
    userController,
} = require('@controllers/backend');

const {
    homeController,
    blogController,
    frontSubscribeController,
    shopController,
    frontContactController,
    authController,
    frontUserController,
    cartController,
    checkoutController,
} = require('@controllers/frontend');
module.exports = {
    itemController,
    dashboardController,
    mainCategoriesController,
    articleCategoriesController,
    productCategoriesController,
    brandController,
    productController,
    articleController,
    sliderController,
    subscribeController,
    contactController,
    settingController,
    orderController,
    couponController,
    advertiseController,
    deliveryController,
    userController,

    homeController,
    frontSubscribeController,
    blogController,
    shopController,
    frontContactController,
    authController,
    frontUserController,
    cartController,
    checkoutController,
};
