module.exports = {
    ERROR_NAME_EMPTY: `Vui lòng nhập tên!`,
    ERROR_NAME_LENGTH: `Độ dài tên không hợp lệ!`,
    ERROR_ORDERING_EMPTY: `Vui lòng nhập thứ tự hiển thị!`,
    ERROR_ORDERING_VALUE: `Giá trị thứ tự hiển thị không hợp lệ`,
    ERROR_ORDERING_LENGTH: `Giá trị thứ tự hiển thị không hợp lệ`,
    ERROR_STATUS_EMPTY: `Vui lòng chọn trạng thái!`,
    ERROR_CATEGORY_EMPTY: `Vui lòng chọn danh mục!`,

    SUCCESS_ADD: `Thêm thành công!`,
    SUCCESS_EDIT: `Sửa thành công!`,
    SUCCESS_DELETE: `Xóa thành công!`,
    SUCCESS_CHANGE_STATUS: `Thay đổi trạng thái thành công!`,
    SUCCESS_CHANGE_ORDERING: `Thay đổi thứ tự hiển thị thành công!`,
    SUCCESS_CHANGE_ISMENU: `Danh mục menu đã được thay đổi!`,
    SUCCESS_CHANGE_URL: `Thay đổi đường dẫn liên kết thành công!`,
    SUCCESS_CHANGE_SPECIAL: `Thay đổi thành đặc biệt!`,
    SUCCESS_CHANGE_SHOW: `Thay đổi thành hiển thị!`,

    // user
    SUCCESS_USER_LOGIN: `Đăng nhập thành công!`,
    SUCCESS_USER_REGISTER: `Đăng ký thành công!`,

    ERROR_USER_LOGIN: `Tài khoản hoặc mật khẩu không đúng!`,
    ERROR_USER_EMAIL_EMPTY: `Vui lòng nhập email!`,
    ERROR_USER_EMAIL_VALUE: `Email không hợp lệ!`,
    ERROR_USER_EMAIL_DUPLICATE: `Email này đã được đăng ký!`,
    ERROR_USER_PASSWORD_EMPTY: `Vui lòng nhập mật khẩu!`,
    ERROR_USER_PASSWORD_VALUE: `Sai mật khẩu!`,
    ERROR_USER_PASSWORD_LENGTH: `Độ dài mật khẩu không hợp lệ (phải từ 3 đến 15 ký tự)!`,
    ERROR_USER_CONFIRMPASSWORD: `Xác minh mật khẩu không đúng!`,
    ERROR_USER_PHONE_EMPTY: `Vui lòng nhập số điện thoại!`,
    ERROR_USER_PHONE_VALUE: `Số điện thoại không đúng!`,
    ERROR_USER_PHONE_LENGTH: `Số điện thoại phải có 10 số!`,
    ERROR_USER_ADDRESS_EMPTY: `Vui lòng nhập địa chỉ!`,
    ERROR_USER_FNAME_EMPTY: `Vui lòng nhập tên!`,
    ERROR_USER_LNAME_EMPTY: `Vui lòng nhập họ!`,

    ERROR_LOCATION_EMPTY: `Vui lòng chọn khu vực!`,
    ERROR_COUPON_EMPTY: `Vui lòng nhập mã giảm giá!`,
    ERROR_COUPON_VALUE: `Mã giảm giá không đúng!`,
    ERROR_COUPON_EXPIRED: `Mã giảm giá này đã hết hạn sử dụng!`,
    ERROR_COUPON_QTY: `Mã giảm giá này đã hết!`,
    ERROR_COUPON_CONDITION: `Điều kiện sử dụng mã giảm giá này không phù hợp!`,
};
